"""Zoo compliance: rights fields and the ATTRIBUTION / SOURCE / CONVERSION documents.

The model zoo's release tooling requires every hosted package to carry MODEL_CARD.md,
LICENSE.md, ATTRIBUTION.md, CONVERSION.md and SOURCE.md, and every catalog row to carry
rights fields (hosting/rights/commercial status, rights holder, licence URL, restrictions).
The submitter-knowable values are derived here; the admin assigns the final rights status.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

from . import __version__
from .workspace import Workspace

COMPLIANCE_FILES = (
    "MODEL_CARD.md",
    "LICENSE.md",
    "ATTRIBUTION.md",
    "CONVERSION.md",
    "SOURCE.md",
)
GENERATED_FILES = ("ATTRIBUTION.md", "CONVERSION.md", "SOURCE.md")
SOURCE_ARTIFACT = "SOURCE_ARTIFACT.json"
GENERATED_MARK = (
    "<!-- generated by sparrow-model-uploader; edit provenance and re-run lint -->"
)

_ATTRIBUTION = ["attribution"]
# Restriction vocabulary as used by the zoo catalog (attribution, sharealike, copyleft, ...).
_LICENSE_RESTRICTIONS: dict[str, list[str]] = {
    "MIT": _ATTRIBUTION,
    "Apache-2.0": _ATTRIBUTION,
    "BSD-2-Clause": _ATTRIBUTION,
    "BSD-3-Clause": _ATTRIBUTION,
    "ISC": _ATTRIBUTION,
    "CC-BY-4.0": _ATTRIBUTION,
    "MPL-2.0": ["attribution", "copyleft", "source_offer"],
    "CC-BY-SA-4.0": ["attribution", "sharealike"],
    "OpenRAIL": ["attribution", "prohibited_uses"],
    "OpenRAIL-M": ["attribution", "prohibited_uses"],
    "Unlicense": [],
    "CC0-1.0": [],
}
_COPYLEFT = ["copyleft", "source_offer"]


def license_restrictions(spdx: str) -> list[str]:
    s = spdx.strip()
    if s in _LICENSE_RESTRICTIONS:
        return list(_LICENSE_RESTRICTIONS[s])
    if re.match(r"^(A|L)?GPL-", s):
        return list(_COPYLEFT)
    return list(_ATTRIBUTION)


def is_http_url(value: Any) -> bool:
    if not isinstance(value, str) or not value or any(c.isspace() for c in value):
        return False
    try:
        parts = urlsplit(value)
    except ValueError:
        return False
    return parts.scheme in ("http", "https") and bool(parts.hostname)


def rights_fields(prov: dict[str, Any]) -> dict[str, Any]:
    """Submitter-side rights fields for the catalog row draft (zoo catalog schema 1.2).

    Intake only admits licences that allow commercial use, so commercial_use is true.
    hosting_status / rights_status / conversion_permission stay pending until a zoo admin
    verifies the licence; rights_record names this submission as the evidence route.
    """
    restrictions = list(
        dict.fromkeys(
            prov.get("restrictions") or license_restrictions(prov.get("license", ""))
        )
    )
    return {
        "commercial_use": True,
        "commercial_use_status": "allowed",
        "hosting_status": "pending_rights",
        "rights_status": "unverified",
        "rights_record": f"sparrow-uploader-submission:{prov.get('model_id', '')}",
        "rights_holder": prov.get("rights_holder") or prov.get("developer", ""),
        "license_source_url": prov.get("license_source_url", ""),
        "original_source_url": prov.get("source", ""),
        "conversion_permission": "pending",
        "restrictions": restrictions,
        "framework_licenses": list(prov.get("framework_licenses") or []),
    }


def provenance_issues(prov: dict[str, Any]) -> tuple[list[str], list[str]]:
    """(errors, warnings) for the rights facts the zoo needs before it can host the weights."""
    errors: list[str] = []
    warnings: list[str] = []
    if not is_http_url(prov.get("source")):
        errors.append(
            "--source must be an http(s) URL of the original weights (pin the revision); "
            "the zoo records it as original_source_url"
        )
    if not is_http_url(prov.get("license_source_url")):
        errors.append(
            "no licence URL: re-run `init --force ... --license-url <URL of the LICENSE file at the "
            "pinned revision>`; the zoo needs it to host the weights"
        )
    if not prov.get("source_weights"):
        warnings.append(
            "no --source-weights recorded: SOURCE.md cannot state the sha256 of the original "
            "weights file the ONNX was converted from"
        )
    if not prov.get("source_revision"):
        warnings.append(
            "no --source-revision recorded (commit, tag or release of the original weights)"
        )
    if not prov.get("display_name"):
        warnings.append(
            "no --display-name recorded; the catalog shows the model id instead of a readable name"
        )
    return errors, warnings


def source_artifact(ws: Workspace, prov: dict[str, Any]) -> dict[str, Any]:
    validate = ws.read_evidence("validate") or {}
    graph = validate.get("graph") or {}
    return {
        "schema_version": "1.0",
        "model_id": ws.model_id,
        "source_artifact": {
            "url": prov.get("source", ""),
            "revision": prov.get("source_revision", ""),
            "files": prov.get("source_weights", []),
            "license": prov.get("license", ""),
            "license_source_url": prov.get("license_source_url", ""),
        },
        "conversion": {
            "framework": prov.get("framework", ""),
            "onnx_version": validate.get("onnx_version"),
            "onnxruntime_version": validate.get("ort_version"),
            "opsets": graph.get("opsets"),
            "uploader_version": __version__,
        },
        "converted_artifact": {
            "file": "1/model.onnx",
            "size_bytes": ws.onnx.stat().st_size if ws.onnx.is_file() else None,
            "sha256": validate.get("onnx_sha256"),
        },
    }


def _card_section(card_text: str, title: str) -> str:
    m = re.search(
        rf"^## {re.escape(title)}\s*$(.*?)(?=^## |\Z)", card_text, re.M | re.S
    )
    return m.group(1).strip() if m else ""


def render_attribution(prov: dict[str, Any]) -> str:
    holder = prov.get("rights_holder") or prov.get("developer", "")
    lines = [
        GENERATED_MARK,
        "# Attribution",
        "",
        f"The weights in `1/model.onnx` are a format conversion of the model published by "
        f"{holder}.",
        "",
        f"- Developer: {prov.get('developer', '')}",
        f"- Rights holder: {holder}",
        f"- Licence: {prov.get('license', '')} ({prov.get('license_source_url', '')})",
        f"- Original weights: {prov.get('source', '')}",
        f"- Reference: {prov.get('reference', '')}",
    ]
    fl = prov.get("framework_licenses") or []
    if fl:
        lines.append(f"- Framework licences: {', '.join(fl)}")
    lines += [
        "",
        "Redistribute this package with LICENSE.md, this file and MODEL_CARD.md, and cite the "
        "reference above in work that uses the model.",
        "",
    ]
    return "\n".join(lines)


def render_source(prov: dict[str, Any], art: dict[str, Any]) -> str:
    conv = art["converted_artifact"]
    lines = [
        GENERATED_MARK,
        "# Source identity",
        "",
        f"- Original weights: {prov.get('source', '')}",
        f"- Revision: {prov.get('source_revision') or 'not recorded'}",
        f"- Licence: {prov.get('license', '')}; licence text: {prov.get('license_source_url', '')}",
        "",
    ]
    files = prov.get("source_weights") or []
    if files:
        lines += ["| Source file | Bytes | sha256 |", "|---|---|---|"]
        lines += [f"| `{f['name']}` | {f['bytes']} | `{f['sha256']}` |" for f in files]
    else:
        lines.append("The sha256 of the original weights file was not recorded.")
    lines += [
        "",
        f"Converted artifact: `{conv['file']}`, {conv['size_bytes']} bytes, sha256 "
        f"`{conv['sha256']}`. Machine-readable copy: `{SOURCE_ARTIFACT}`.",
        "",
    ]
    return "\n".join(lines)


def render_conversion(
    prov: dict[str, Any], art: dict[str, Any], card_text: str, parity_md: str
) -> str:
    conv = art["conversion"]
    recipe = (
        _card_section(card_text, "Conversion recipe")
        or "Not described in MODEL_CARD.md."
    )
    return "\n".join(
        [
            GENERATED_MARK,
            "# Conversion record",
            "",
            f"- Original framework: {prov.get('framework') or 'not recorded'}",
            f"- ONNX opsets: {json.dumps(conv['opsets'])}",
            f"- Validated with onnx {conv['onnx_version']}, onnxruntime "
            f"{conv['onnxruntime_version']}, sparrow-model-uploader {conv['uploader_version']}",
            f"- Output: `1/model.onnx`, sha256 `{art['converted_artifact']['sha256']}`",
            "",
            "## Procedure",
            "",
            recipe,
            "",
            "## Parity with the original model",
            "",
            parity_md,
            "",
            "Full measurements: `evidence/parity_raw.json` and `evidence/parity_pipeline.json` "
            "in the submission.",
            "",
        ]
    )


def write_compliance(ws: Workspace, prov: dict[str, Any], parity_md: str) -> list[str]:
    """Write the generated documents and SOURCE_ARTIFACT.json. A document without the
    generated marker was written by hand and is kept. Returns the names that were kept."""
    card = ws.bundle / "MODEL_CARD.md"
    card_text = card.read_text(encoding="utf-8") if card.is_file() else ""
    art = source_artifact(ws, prov)
    docs = {
        "ATTRIBUTION.md": render_attribution(prov),
        "SOURCE.md": render_source(prov, art),
        "CONVERSION.md": render_conversion(prov, art, card_text, parity_md),
    }
    kept: list[str] = []
    for name, text in docs.items():
        path = ws.bundle / name
        if path.is_file() and GENERATED_MARK not in path.read_text(encoding="utf-8"):
            kept.append(name)
            continue
        path.write_text(text, encoding="utf-8")
    (ws.bundle / SOURCE_ARTIFACT).write_text(
        json.dumps(art, indent=2) + "\n", encoding="utf-8"
    )
    return kept


_TODO = re.compile(r"(?<!\w)(TODO|TBD)(?!\w)|\[\s*(FILL IN|NEEDS USER INPUT)", re.I)


def placeholder_lines(text: str) -> list[str]:
    return [ln.strip() for ln in text.splitlines() if _TODO.search(ln)]


def file_entry(path: Path) -> dict[str, Any]:
    from .workspace import sha256_file

    return {
        "name": path.name,
        "bytes": path.stat().st_size,
        "sha256": sha256_file(path),
    }
